spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

  output:
    ansi:
      enabled: DETECT

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5

server:
  port: 9999
  context-path: /
  tomcat:
    max-threads: 500
    min-spare-threads: 30
    uri-encoding: utf-8
    basedir: /opt/apps/hello
    accesslog:
      enabled: true

logging:
  path: /opt/apps/hello
