spring:
  profiles:
    active: test
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

---
spring:
  profiles: test

boot:
  secret: a

server:
  port: 8081

---
spring:
  profiles: dev

boot:
  secret: a

server:
  port: 8082