spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

  output:
    ansi:
      enabled: DETECT

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5

server:
  port: 8080