spring:
  profiles:
    active: test
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  output:
    ansi:
      enabled: DETECT

#测试环境
---
spring:
  profiles: test

boot:
  secret: a

server:
  port: 8081

#开发环境
---
spring:
  profiles: dev

boot:
  secret: a

server:
  port: 8082