
spring:
  profiles:
    active: dev

  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: Asia/Shanghai
  output:
      ansi:
        enabled: DETECT

  datasource:
      driver-class-name: com.mysql.jdbc.Driver

  hikari:
    maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
    maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上

#dev
---
spring:
  profiles: dev
  datasource:
    username: root
    password: pwd
    url: jdbc:mysql://localhost:3306/spring_boot

server:
  port: 8081


#test
---
spring:
  profiles: test
  datasource:
    username: name
    password: pwd
    url: jdbc:mysql://localhost:3306/spring_boot

server:
  port: 8082


#prod
---
spring:
  profiles: prod
  datasource:
    username: name
    password: pwd
    url: jdbc:mysql://localhost:3306/spring_boot

server:
  port: 8765