
spring:
  profiles:
    active: dev

  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: Asia/Shanghai
  output:
      ansi:
        enabled:

  datasource:
      driver-class-name: com.mysql.jdbc.Driver

#dev
---
spring:
  profiles: dev
  datasource:
    username: root
    password: xx
    url: jdbc:mysql://localhost:3306/spring_boot

server:
  port: 8081


#test
---
spring:
  profiles: test
  datasource:
    username: xx
    password: xx
    url: jdbc:mysql://localhost:3306/spring_boot

server:
  port: 8082


#prod
---
spring:
  profiles: prod
  datasource:
    username: xx
    password: xx
    url: jdbc:mysql://localhost:3306/spring_boot

server:
  port: 8765