
spring:
  profiles:
    active: dev

  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: Asia/Shanghai
  output:
      ansi:
        enabled: DETECT

  datasource:
      driver-class-name: com.mysql.jdbc.Driver

  aop:
    auto: true
    proxy-target-class: true

  hikari:
    maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
    maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上

#actuator
management:
  context-path: /admin
  port: 8181
  security:
    enabled: false


#dev
---
spring:
  profiles: dev
  datasource:
    username: root
    password: andyadc
    url: jdbc:mysql://localhost:3306/spring_boot

  redis:
    host: localhost
    database: 0
    port: 6379
    password:

  mail:
    default-encoding: utf-8
    host: smtp.163.com
    username: andaicheng@163.com
    password: pwd

# set log path. logging.path(Spring Environment) <---> LOG_PATH(System Property)
logging:
  path: d:/temp/logs/springboot/quickstart1

server:
  port: 8081

#test
---
spring:
  profiles: test
  datasource:
    username: name
    password: pwd
    url: jdbc:mysql://localhost:3306/spring_boot

logging:
  path: d:/temp/logs/springboot/quickstart2

server:
  port: 8082


#prod
---
spring:
  profiles: prod
  datasource:
    username: name
    password: pwd
    url: jdbc:mysql://localhost:3306/spring_boot

server:
  port: 8765